---
name: Build dev branch and upload

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkita64
    env:
      IS_DEV: true

    steps:
    - name: Show environment info
      run: dkp-pacman -Q

    - name: Checkout project
      uses: actions/checkout@v4
      with:
        submodules: recursive
        ref: dev

    - name: Build project
      run: make

    - name: Create release structure
      run: |
        mkdir -p release/switch/.overlays
        mkdir -p release/config
        cp QuickNTP.ovl release/switch/.overlays/
        cp quickntp.ini release/config/

    - name: Read app version from makefile
      run: |
        echo "version=$(make print-APP_VERSION)" >> $GITHUB_ENV

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: quickntp-${{ env.version }}-dev
        path: release/
        include-hidden-files: true
